export const userInputs = [
  {
    id: "name",
    label: "Full Name",
    type: "text",
    placeholder: "John Doe",
  },
  {
    id: "email",
    label: "Email",
    type: "email",
    placeholder: "john.doe@example.com",
  },
  {
    id: "rollno",
    label: "Roll No",
    type: "number",
    placeholder: "123",
  },
  {
    id: "contact",
    label: "Contact No",
    type: "tel",
    placeholder: "+1 234 567 89",
  },
  {
    id: "password",
    label: "Password",
    type: "password",
    placeholder: "********",
  },
  {
    id: "address",
    label: "Address",
    type: "text",
    placeholder: "123 Main St, City",
  },
  {
    id: "fathersname",
    label: "Father's Name",
    type: "text",
    placeholder: "Michael Doe",
  },
  {
    id: "fathersoccupation",
    label: "Father's Occupation",
    type: "text",
    placeholder: "Engineer",
  },
  {
    id: "telephone",
    label: "Telephone No",
    type: "tel",
    placeholder: "+1 987 654 321",
  },
  {
    id: "fathersemail",
    label: "Father's Email",
    type: "email",
    placeholder: "michael.doe@example.com",
  },
  {
    id: "batch",
    label: "Batch",
    type: "text",
    placeholder: "Batch 1",
  },
  {
    id: "age",
    label: "Age",
    type: "text",
    placeholder: "25",
  },
  {
    id: "gender",
    label: "Gender",
    type: "text",
    placeholder: "Male",
  },
  {
    id: "status",
    label: "Activity Status",
    type: "text",
    placeholder: "Active",
  },
];
